services:
  s3:
    image: versity/versitygw:latest
    ports:
      - "7070:7070"
    environment:
      ROOT_ACCESS_KEY: s3
      ROOT_SECRET_KEY: s3
    command: >
      posix /data
    volumes:
      - ./s3-data:/data

