autoInstallPeers: false
publicHoistPattern:
  - "*import-in-the-middle*"
  - "*require-in-the-middle*"
overrides:
  "kysely": "^0.29.0"
allowedDeprecatedVersions:
  "@esbuild-kit/core-utils": "*"
  "@esbuild-kit/esm-loader": "*"
ignoredOptionalDependencies:
  - unrun
packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  "@swc/core": true
  esbuild: true
  sharp: true
