autoInstallPeers: false
publicHoistPattern:
  - "*import-in-the-middle*"
  - "*require-in-the-middle*"
overrides:
  "@types/react": "19.2.15"
  "@types/react-dom": "19.2.3"
allowedDeprecatedVersions:
  "@esbuild-kit/core-utils": "*"
  "@esbuild-kit/esm-loader": "*"
ignoredOptionalDependencies:
  - unrun
packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  "@swc/core": true
  esbuild: true
  sharp: true
