name: Playwright Tests (sign-up-enabled)
env:
  TURBO_TELEMETRY_DISABLED: 1
  NEXT_TELEMETRY_DISABLED: 1
  DO_NOT_TRACK: 1
  NEXT_PUBLIC_BASE_URL: http://localhost:3000
  NEXT_PUBLIC_SITE_NAME: app
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  ANALYSIS_SENTRY_DSN: ${{ secrets.ANALYSIS_SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  AUTH_DISABLE_SIGNUP: 0
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-run-test-sign-up-enabled:
    services:
      mailpit:
        image: axllent/mailpit
        ports:
          - 1025:1025
          - 8025:8025
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      s3:
        image: versity/versitygw:latest
        env:
          ROOT_ACCESS_KEY: s3
          ROOT_SECRET_KEY: s3
          VGW_BACKEND: posix
          VGW_BACKEND_ARG: /tmp
        ports:
          - 7070:7070
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/playwright-setup
        with:
          signup-enabled: "true"

      - name: Run Playwright tests (sign-up-enabled)
        run: pnpm run e2e:sign-up-enabled
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-sign-up-enabled-test-results
          path: ./packages/e2e-web/test-results
          retention-days: 30
